// ─── Level Definitions ─────────────────────────────────────────────────────────
// Difficulty progression: L1 very easy → L5 needs multiple tries

export const LEVELS = [
  {
    id: 1,
    name: 'First Steps',
    description: 'Get used to the controls. Lots of room to land.',
    difficulty: 'EASY',
    hexCount: 50,
    hexRadius: 2.2,
    hexMinSpacingExtra: 0.5,   // extra gap beyond 2*radius
    startingPower: 10,
    powerPerRound: 3,          // power grows slowly
    roundsToWin: 5,
    movingTileCount: 0,
    timedTileCount: 0,
    timedTileDuration: 4,
  },
  {
    id: 2,
    name: 'Open Field',
    description: 'Fewer tiles spread across the whole platform.',
    difficulty: 'NORMAL',
    hexCount: 35,
    hexRadius: 2.0,
    hexMinSpacingExtra: 0.8,
    startingPower: 15,
    powerPerRound: 4,
    roundsToWin: 8,
    movingTileCount: 0,
    timedTileCount: 0,
    timedTileDuration: 4,
  },
  {
    id: 3,
    name: 'Moving Targets',
    description: 'Some tiles refuse to stay still. Track them carefully.',
    difficulty: 'MEDIUM',
    hexCount: 28,
    hexRadius: 2.0,
    hexMinSpacingExtra: 0.9,
    startingPower: 20,
    powerPerRound: 5,
    roundsToWin: 10,
    movingTileCount: 4,
    timedTileCount: 0,
    timedTileDuration: 4,
  },
  {
    id: 4,
    name: 'Hot Seat',
    description: 'Orange tiles crack after 4 seconds. Land and shoot fast.',
    difficulty: 'HARD',
    hexCount: 22,
    hexRadius: 1.9,
    hexMinSpacingExtra: 1.0,
    startingPower: 25,
    powerPerRound: 6,
    roundsToWin: 12,
    movingTileCount: 4,
    timedTileCount: 3,
    timedTileDuration: 4,
  },
  {
    id: 5,
    name: 'Expert Circuit',
    description: 'Few tiles. Fast tiles. Ticking tiles. Good luck.',
    difficulty: 'EXPERT',
    hexCount: 22,
    hexRadius: 1.8,
    hexMinSpacingExtra: 1.2,
    startingPower: 30,
    powerPerRound: 7,
    roundsToWin: 15,
    movingTileCount: 6,
    timedTileCount: 4,
    timedTileDuration: 3,
  },
];
